services:
  http-server-projeto-korp:
    build:
      context: .
      dockerfile: Dockerfile
    image: http-server-projeto-korp:latest
    container_name: http-server-projeto-korp
    networks:
      - projeto-korp-net
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-projeto-korp
    depends_on:
      - http-server-projeto-korp
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - projeto-korp-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus-projeto-korp
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - projeto-korp-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana-projeto-korp
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    networks:
      - projeto-korp-net
    restart: unless-stopped

networks:
  projeto-korp-net:
    name: projeto-korp-net
